
[tool.isort]
lines_between_sections=0
multi_line_output = 3

[tool.pylint]
disable = [
    "missing-module-docstring",
    "missing-class-docstring",
    "missing-function-docstring",
    "C0103"
]
max-line-length=160
max-locals=20
min-public-methods=1
